// Local destination database. Replace this file with real data while keeping the same schema.
// source = "seed_google_maps_manual" means the place is a real-world destination seeded from public map/travel references.
// It is not live API data yet. Keep product planning fields here because Google Maps does not provide them reliably.
window.destinationDatabase = [
  {
    id: "osaka-dotonbori",
    source: "mock",
    name: "道頓堀",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "難波", lat: 34.6687, lng: 135.5010 },
    category: "food",
    display: { rating: 4.5, tags: ["美食", "夜景"], priceHint: 1200 },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "medium", mealFriendly: true },
  },
  {
    id: "osaka-castle",
    source: "mock",
    name: "大阪城",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "大阪城公園", lat: 34.6873, lng: 135.5262 },
    category: "culture",
    display: { rating: 4.4, tags: ["文化", "公園"], priceHint: 600 },
    planning: { defaultStayMinutes: 120, importance: 5, intensity: "medium", mealFriendly: false },
  },
  {
    id: "osaka-umeda-sky",
    source: "mock",
    name: "梅田藍天大廈",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "梅田", lat: 34.7053, lng: 135.4897 },
    category: "photo",
    display: { rating: 4.4, tags: ["展望", "好拍"], priceHint: 1500 },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "low", bestTimeWindows: [{ label: "night_view", preferredTime: "18:00", reason: "夜景" }] },
    reservation: { required: true, type: "ticket", status: "needed", suggestedTime: "18:00", note: "展望台夜景時段建議先確認票券或入場時段。", lockTimeline: true },
  },
  {
    id: "osaka-shinsekai",
    source: "mock",
    name: "新世界",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "天王寺", lat: 34.6525, lng: 135.5063 },
    category: "food",
    display: { rating: 4.2, tags: ["美食", "街區"], priceHint: 1000 },
    planning: { defaultStayMinutes: 90, importance: 3, intensity: "medium", mealFriendly: true },
  },
  {
    id: "osaka-kuromon",
    source: "mock",
    name: "黑門市場",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "日本橋", lat: 34.6654, lng: 135.5064 },
    category: "food",
    display: { rating: 4.1, tags: ["市場", "美食"], priceHint: 1600 },
    planning: { defaultStayMinutes: 75, importance: 3, intensity: "medium", mealFriendly: true, bestTimeWindows: [{ label: "market_morning", preferredTime: "10:00" }] },
  },
  {
    id: "osaka-namba-parks",
    source: "mock",
    name: "難波 Parks",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "難波", lat: 34.6617, lng: 135.5019 },
    category: "shopping",
    display: { rating: 4.2, tags: ["購物", "休息"], priceHint: 0 },
    planning: { defaultStayMinutes: 90, importance: 3, intensity: "low", mealFriendly: true },
  },
  {
    id: "osaka-usj",
    source: "mock",
    name: "日本環球影城",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "此花", lat: 34.6654, lng: 135.4323 },
    category: "experience",
    display: { rating: 4.6, tags: ["主題樂園", "大景點"], priceHint: 8600 },
    planning: { defaultStayMinutes: 420, importance: 5, intensity: "high", needsReservation: true },
    reservation: { required: true, type: "ticket", status: "needed", suggestedTime: "09:00", note: "大型主題樂園通常需要先買票，熱門日期也要確認入場或快速通關。", lockTimeline: true },
  },
  {
    id: "osaka-sumiyoshi",
    source: "mock",
    name: "住吉大社",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "住吉", lat: 34.6127, lng: 135.4938 },
    category: "culture",
    display: { rating: 4.4, tags: ["神社", "文化"], priceHint: 0 },
    planning: { defaultStayMinutes: 80, importance: 3, intensity: "low" },
  },
  {
    id: "osaka-shinsaibashi",
    source: "mock",
    name: "心齋橋商店街",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "心齋橋", lat: 34.6744, lng: 135.5013 },
    category: "shopping",
    display: { rating: 4.3, tags: ["購物", "街區"], priceHint: 0 },
    planning: { defaultStayMinutes: 120, importance: 4, intensity: "medium", mealFriendly: true },
  },
  {
    id: "kyoto-kiyomizu",
    source: "mock",
    name: "清水寺",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "東山", lat: 34.9949, lng: 135.7850 },
    category: "culture",
    display: { rating: 4.5, tags: ["寺院", "文化", "好拍"], priceHint: 400, description: "京都代表性寺院，適合安排在東山散步路線中。" },
    planning: { defaultStayMinutes: 120, importance: 5, intensity: "medium", needsReservation: false },
  },
  {
    id: "kyoto-fushimi-inari",
    source: "mock",
    name: "伏見稻荷大社",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "伏見", lat: 34.9671, lng: 135.7727 },
    category: "culture",
    display: { rating: 4.6, tags: ["神社", "千本鳥居", "好拍"], priceHint: 0, description: "千本鳥居是京都經典畫面，清晨人較少也更好拍。" },
    planning: { defaultStayMinutes: 120, importance: 5, intensity: "medium", bestTimeWindows: [{ label: "morning_photo", preferredTime: "07:00", reason: "避開人潮" }] },
  },
  {
    id: "kyoto-arashiyama",
    source: "mock",
    name: "嵐山竹林",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "嵐山", lat: 35.0170, lng: 135.6719 },
    category: "nature",
    display: { rating: 4.4, tags: ["自然", "竹林", "散步"], priceHint: 0, description: "適合半日散步，可搭配渡月橋、天龍寺與周邊小店。" },
    planning: { defaultStayMinutes: 150, importance: 5, intensity: "medium" },
  },
  {
    id: "kyoto-nishiki",
    source: "mock",
    name: "錦市場",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "四條", lat: 35.0050, lng: 135.7647 },
    category: "food",
    display: { rating: 4.2, tags: ["市場", "美食", "伴手禮"], priceHint: 1800, description: "京都市中心的美食市場，適合當午餐或下午小吃段落。" },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "medium", mealFriendly: true },
    reservation: { required: false, type: "restaurant", status: "optional", suggestedTime: "12:00", note: "市場本身不用預約，但若之後替換成名店餐廳，需要保留餐廳預約欄位。", lockTimeline: false },
  },
  {
    id: "kyoto-gion",
    source: "mock",
    name: "祇園",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "祇園", lat: 35.0037, lng: 135.7786 },
    category: "culture",
    display: { rating: 4.3, tags: ["街區", "文化", "夜晚"], priceHint: 0, description: "京都傳統街區，傍晚到夜間氛圍好，可接續東山或鴨川。" },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "low", bestTimeWindows: [{ label: "evening_walk", preferredTime: "17:30" }] },
  },
  {
    id: "kyoto-kinkakuji",
    source: "mock",
    name: "金閣寺",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "北區", lat: 35.0394, lng: 135.7292 },
    category: "culture",
    display: { rating: 4.5, tags: ["寺院", "庭園", "文化"], priceHint: 500, description: "京都北區代表景點，適合與龍安寺、北野天滿宮排在同區。" },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "low" },
  },
  {
    id: "osaka-aquarium-kaiyukan",
    source: "seed_google_maps_manual",
    name: "海遊館",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "天保山", lat: 34.6545, lng: 135.4289 },
    category: "experience",
    display: { rating: 4.4, tags: ["水族館", "親子", "室內", "雨天備案"], priceHint: 2700, description: "大阪灣區代表水族館，適合雨天、親子或想把節奏放慢的半日行程。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Osaka+Aquarium+Kaiyukan" },
    planning: { defaultStayMinutes: 150, importance: 4, intensity: "medium", needsReservation: true },
    reservation: { required: true, type: "ticket", status: "optional", suggestedTime: "10:00", note: "熱門假日建議先確認票券與入館時段。", lockTimeline: false },
  },
  {
    id: "osaka-harukas-300",
    source: "seed_google_maps_manual",
    name: "阿倍野 Harukas 300",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "天王寺", lat: 34.6459, lng: 135.5135 },
    category: "photo",
    display: { rating: 4.4, tags: ["展望", "夜景", "好拍", "室內"], priceHint: 2000, description: "天王寺區的高樓展望台，適合安排在傍晚或晚餐前後。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Harukas+300+Osaka" },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "low", bestTimeWindows: [{ label: "sunset_view", preferredTime: "17:30", reason: "夕景/夜景" }] },
    reservation: { required: true, type: "ticket", status: "optional", suggestedTime: "17:30", note: "展望台夕景與夜景時段建議確認票券。", lockTimeline: false },
  },
  {
    id: "osaka-shitennoji",
    source: "seed_google_maps_manual",
    name: "四天王寺",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "天王寺", lat: 34.6547, lng: 135.5165 },
    category: "culture",
    display: { rating: 4.2, tags: ["寺院", "文化", "庭園"], priceHint: 300, description: "大阪歷史感較強的寺院景點，可和天王寺、新世界或阿倍野排在同一天。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Shitennoji+Osaka" },
    planning: { defaultStayMinutes: 75, importance: 3, intensity: "low" },
  },
  {
    id: "osaka-tennoji-zoo",
    source: "seed_google_maps_manual",
    name: "天王寺動物園",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "天王寺", lat: 34.6500, lng: 135.5080 },
    category: "experience",
    display: { rating: 4.1, tags: ["動物園", "親子", "戶外"], priceHint: 500, description: "適合親子或慢節奏旅程，位置靠近新世界與天王寺商圈。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Tennoji+Zoo+Osaka" },
    planning: { defaultStayMinutes: 120, importance: 3, intensity: "medium" },
  },
  {
    id: "osaka-hozenji-yokocho",
    source: "seed_google_maps_manual",
    name: "法善寺橫丁",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "難波", lat: 34.6680, lng: 135.5020 },
    category: "food",
    display: { rating: 4.3, tags: ["街區", "美食", "夜晚", "好拍"], priceHint: 1200, description: "難波附近的小巷街區，適合接在道頓堀或晚餐前後。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Hozenji+Yokocho+Osaka" },
    planning: { defaultStayMinutes: 45, importance: 3, intensity: "low", mealFriendly: true, bestTimeWindows: [{ label: "evening_walk", preferredTime: "18:30", reason: "夜晚氛圍" }] },
  },
  {
    id: "osaka-amerikamura",
    source: "seed_google_maps_manual",
    name: "美國村",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "心齋橋", lat: 34.6720, lng: 135.4970 },
    category: "shopping",
    display: { rating: 4.0, tags: ["街區", "購物", "潮流", "好拍"], priceHint: 0, description: "靠近心齋橋的年輕潮流街區，適合和購物、咖啡行程一起安排。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Amerikamura+Osaka" },
    planning: { defaultStayMinutes: 75, importance: 3, intensity: "medium", mealFriendly: true },
  },
  {
    id: "osaka-nakazakicho",
    source: "seed_google_maps_manual",
    name: "中崎町",
    location: { countryCode: "JP", countryName: "Japan", city: "osaka", cityName: "大阪", area: "梅田", lat: 34.7075, lng: 135.5050 },
    category: "food",
    display: { rating: 4.2, tags: ["咖啡", "街區", "好拍", "慢逛"], priceHint: 1200, description: "梅田附近的咖啡與小店街區，適合放在購物日或下午休息段。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Nakazakicho+Osaka" },
    planning: { defaultStayMinutes: 90, importance: 3, intensity: "low", mealFriendly: true },
  },
  {
    id: "kyoto-ninenzaka-sannenzaka",
    source: "seed_google_maps_manual",
    name: "二年坂 / 三年坂",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "東山", lat: 34.9980, lng: 135.7807 },
    category: "culture",
    display: { rating: 4.4, tags: ["街區", "文化", "好拍", "伴手禮"], priceHint: 0, description: "清水寺周邊經典散步路線，適合和清水寺、八坂神社或祇園連成東山一日。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ninenzaka+Sannenzaka+Kyoto" },
    planning: { defaultStayMinutes: 90, importance: 5, intensity: "medium", mealFriendly: true },
  },
  {
    id: "kyoto-yasaka-shrine",
    source: "seed_google_maps_manual",
    name: "八坂神社",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "祇園", lat: 35.0037, lng: 135.7788 },
    category: "culture",
    display: { rating: 4.4, tags: ["神社", "文化", "夜晚"], priceHint: 0, description: "位於祇園旁，適合接續東山散步，也可安排在傍晚到夜間。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Yasaka+Shrine+Kyoto" },
    planning: { defaultStayMinutes: 60, importance: 4, intensity: "low", bestTimeWindows: [{ label: "evening_walk", preferredTime: "17:00", reason: "祇園動線" }] },
  },
  {
    id: "kyoto-ginkakuji",
    source: "seed_google_maps_manual",
    name: "銀閣寺",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "北白川", lat: 35.0270, lng: 135.7982 },
    category: "culture",
    display: { rating: 4.5, tags: ["寺院", "庭園", "文化"], priceHint: 500, description: "京都東北側的代表寺院，適合和哲學之道排在同區。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ginkakuji+Kyoto" },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "low" },
  },
  {
    id: "kyoto-philosophers-path",
    source: "seed_google_maps_manual",
    name: "哲學之道",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "北白川", lat: 35.0252, lng: 135.7948 },
    category: "nature",
    display: { rating: 4.3, tags: ["散步", "自然", "街區", "櫻花"], priceHint: 0, description: "適合慢步調散策，可和銀閣寺、南禪寺方向搭配。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Philosopher%27s+Path+Kyoto" },
    planning: { defaultStayMinutes: 90, importance: 3, intensity: "low", bestTimeWindows: [{ label: "morning_walk", preferredTime: "09:00", reason: "散步" }] },
  },
  {
    id: "kyoto-nijo-castle",
    source: "seed_google_maps_manual",
    name: "二條城",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "二條", lat: 35.0142, lng: 135.7482 },
    category: "culture",
    display: { rating: 4.4, tags: ["城郭", "文化", "庭園"], priceHint: 1300, description: "京都市中心偏西的世界遺產城郭，適合和市中心或北野方向安排。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Nijo+Castle+Kyoto" },
    planning: { defaultStayMinutes: 120, importance: 5, intensity: "medium" },
    reservation: { required: false, type: "ticket", status: "optional", suggestedTime: "10:00", note: "部分展覽或旺季可先確認門票與開放資訊。", lockTimeline: false },
  },
  {
    id: "kyoto-ryoanji",
    source: "seed_google_maps_manual",
    name: "龍安寺",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "衣笠", lat: 35.0345, lng: 135.7183 },
    category: "culture",
    display: { rating: 4.4, tags: ["寺院", "庭園", "文化"], priceHint: 600, description: "以枯山水石庭聞名，適合和金閣寺安排在京都北區路線。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ryoanji+Kyoto" },
    planning: { defaultStayMinutes: 75, importance: 4, intensity: "low" },
  },
  {
    id: "kyoto-kyoto-tower",
    source: "seed_google_maps_manual",
    name: "京都塔",
    location: { countryCode: "JP", countryName: "Japan", city: "kyoto", cityName: "京都", area: "京都站", lat: 34.9875, lng: 135.7593 },
    category: "photo",
    display: { rating: 4.1, tags: ["展望", "夜景", "車站", "室內"], priceHint: 900, description: "京都站前的展望景點，適合抵達日、離開日前後或雨天備案。", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Kyoto+Tower" },
    planning: { defaultStayMinutes: 60, importance: 3, intensity: "low", bestTimeWindows: [{ label: "night_view", preferredTime: "18:00", reason: "夜景" }] },
  },
  {
    id: "tokyo-sensoji",
    source: "mock",
    name: "淺草寺",
    location: { countryCode: "JP", countryName: "Japan", city: "tokyo", cityName: "東京", area: "淺草", lat: 35.7148, lng: 139.7967 },
    category: "culture",
    display: { rating: 4.5, tags: ["文化", "街區"], priceHint: 0 },
    planning: { defaultStayMinutes: 100, importance: 5, intensity: "medium" },
  },
  {
    id: "tokyo-skytree",
    source: "mock",
    name: "晴空塔",
    location: { countryCode: "JP", countryName: "Japan", city: "tokyo", cityName: "東京", area: "押上", lat: 35.7101, lng: 139.8107 },
    category: "photo",
    display: { rating: 4.4, tags: ["展望", "好拍"], priceHint: 2100 },
    planning: { defaultStayMinutes: 110, importance: 4, intensity: "low" },
    reservation: { required: true, type: "ticket", status: "needed", suggestedTime: "17:30", note: "展望台可現場購票，但指定時段與夕景/夜景建議先買票。", lockTimeline: true },
  },
  {
    id: "tokyo-shibuya",
    source: "mock",
    name: "澀谷 Scramble",
    location: { countryCode: "JP", countryName: "Japan", city: "tokyo", cityName: "東京", area: "澀谷", lat: 35.6595, lng: 139.7005 },
    category: "photo",
    display: { rating: 4.4, tags: ["街區", "好拍"], priceHint: 0 },
    planning: { defaultStayMinutes: 80, importance: 4, intensity: "medium" },
  },
  {
    id: "tokyo-meiji",
    source: "mock",
    name: "明治神宮",
    location: { countryCode: "JP", countryName: "Japan", city: "tokyo", cityName: "東京", area: "原宿", lat: 35.6764, lng: 139.6993 },
    category: "culture",
    display: { rating: 4.6, tags: ["神社", "森林"], priceHint: 0 },
    planning: { defaultStayMinutes: 100, importance: 5, intensity: "low" },
  },
  {
    id: "tokyo-ginza",
    source: "mock",
    name: "銀座",
    location: { countryCode: "JP", countryName: "Japan", city: "tokyo", cityName: "東京", area: "銀座", lat: 35.6717, lng: 139.7650 },
    category: "shopping",
    display: { rating: 4.3, tags: ["購物", "餐廳"], priceHint: 0 },
    planning: { defaultStayMinutes: 120, importance: 4, intensity: "medium", mealFriendly: true },
  },
  {
    id: "tokyo-tsukiji",
    source: "mock",
    name: "築地場外市場",
    location: { countryCode: "JP", countryName: "Japan", city: "tokyo", cityName: "東京", area: "築地", lat: 35.6655, lng: 139.7707 },
    category: "food",
    display: { rating: 4.2, tags: ["市場", "美食"], priceHint: 1800 },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "medium", mealFriendly: true },
  },
  {
    id: "seoul-gyeongbok",
    source: "mock",
    name: "景福宮",
    location: { countryCode: "KR", countryName: "South Korea", city: "seoul", cityName: "首爾", area: "鐘路", lat: 37.5796, lng: 126.9770 },
    category: "culture",
    display: { rating: 4.6, tags: ["文化", "韓服"], priceHint: 3000 },
    planning: { defaultStayMinutes: 120, importance: 5, intensity: "medium" },
  },
  {
    id: "seoul-bukchon",
    source: "mock",
    name: "北村韓屋村",
    location: { countryCode: "KR", countryName: "South Korea", city: "seoul", cityName: "首爾", area: "鐘路", lat: 37.5826, lng: 126.9830 },
    category: "photo",
    display: { rating: 4.3, tags: ["好拍", "街區"], priceHint: 0 },
    planning: { defaultStayMinutes: 90, importance: 4, intensity: "medium" },
  },
  {
    id: "seoul-myeongdong",
    source: "mock",
    name: "明洞",
    location: { countryCode: "KR", countryName: "South Korea", city: "seoul", cityName: "首爾", area: "中區", lat: 37.5636, lng: 126.9820 },
    category: "shopping",
    display: { rating: 4.2, tags: ["購物", "美食"], priceHint: 0 },
    planning: { defaultStayMinutes: 120, importance: 4, intensity: "medium", mealFriendly: true },
  },
  {
    id: "seoul-namsan",
    source: "mock",
    name: "南山首爾塔",
    location: { countryCode: "KR", countryName: "South Korea", city: "seoul", cityName: "首爾", area: "龍山", lat: 37.5512, lng: 126.9882 },
    category: "photo",
    display: { rating: 4.4, tags: ["展望", "夜景"], priceHint: 16000 },
    planning: { defaultStayMinutes: 100, importance: 4, intensity: "low", bestTimeWindows: [{ label: "night_view", preferredTime: "18:30" }] },
    reservation: { required: true, type: "ticket", status: "needed", suggestedTime: "18:30", note: "夜景時段可先確認票券、纜車排隊與營業時間。", lockTimeline: true },
  },
  {
    id: "seoul-hongdae",
    source: "mock",
    name: "弘大商圈",
    location: { countryCode: "KR", countryName: "South Korea", city: "seoul", cityName: "首爾", area: "麻浦", lat: 37.5563, lng: 126.9236 },
    category: "food",
    display: { rating: 4.3, tags: ["美食", "街區"], priceHint: 12000 },
    planning: { defaultStayMinutes: 140, importance: 4, intensity: "medium", mealFriendly: true },
  },
  {
    id: "seoul-coex",
    source: "mock",
    name: "COEX 星空圖書館",
    location: { countryCode: "KR", countryName: "South Korea", city: "seoul", cityName: "首爾", area: "江南", lat: 37.5126, lng: 127.0588 },
    category: "shopping",
    display: { rating: 4.4, tags: ["購物", "好拍"], priceHint: 0 },
    planning: { defaultStayMinutes: 110, importance: 4, intensity: "low" },
  },
];

